import React from 'react';

class Inbox extends React.Component {
  render() {
    return (
      <div>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
        <h1>inbox</h1>
      </div>
    );
  }
}

export default Inbox;
